### ISSUE TITLE
Initialize database with testdata

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#27]
## What?

Upload some testdata to the database automatically for test framework usage

### Tasks:

- [x] Create a new "tests" folder, populate it with some random data. (Ask Marco)
- [x] Create a new testing.py (possibly initializing the test framework) and read the test data, upload it via http client to the flask server (see API - POST /api/projects).
- [ ] Create new docker-compose-test.yml that runs the tests as new python container
- [ ] Let travis.yml run the docker-compose-test.yml file
- [ ] Write integration tests for the existing api endpoint (see wiki page)

**Comment by henderkes** [comment]
> Create a new testing.py (possibly initializing the test framework) and read the test data, upload it via http client to the flask server (see API - POST /api/projects).

/api/projects now supports file upload as well as json/json5, please test both

**Comment by markwitz** [comment]
I think we should populate the database outside the docker container outside a docker container.
Travis should be called in the script part in before-script we start and compose the container and run the test using pytest from outside there is a python library which would even allow us to reference the docker containers running on the system by their docker name. Additionaly to that we can provide a simple python sript wich runs a routine to populate the database for manual testing.
